version: "3.8"
services:
  api:
    build: ./backend
    ports:
      - 8001:8001
    volumes: 
      - ./backend/:/app
      - /app/node_modules
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
  app:
    build: 
      context: ./front-end
      target: build
    ports:
      - 8000:8080
    volumes: 
      - ./front-end/:/app
      - /app/node_modules
